
steps:

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

# test with node 6
- task: NodeTool@0
  displayName: Use Node 6.10.3
  inputs:
    versionSpec: "6.10.3"  

- script: npm test
  displayName: 'npm test'
